import greyknights from "./composableData/greyknights.json";
import custodes from "./composableData/custodes.json";
import votann from "./composableData/votann.json";
import chaosknights from "./composableData/chaosknights.json";

// COMPOSABLE[faction][uid] = family definition (base + slots + choices).
// Generated by scripts/bsdata-import/sync.mjs - re-run that to refresh from
// BSData, don't hand-edit these JSON files.
export const COMPOSABLE = { greyknights, custodes, votann, chaosknights };
