// ─── FACTION: ADEPTUS CUSTODES ────────────────────────────────────────────────
// Weapon note: Ka'tah (army rule) lets each unit pick Dacatarai (SH1 melee) or
// Rendax (Lethal Hits melee) before each Fight phase. Rows labelled "Da" / "Re"
// reflect those stances. Units without meaningful melee get a single row.
// D values are averages: D6=3.5, D6+1=4.5, D6+2=5.5, D6+3=6.5, D3=2.

export const CHARS = {
    none:     {name:"None",          pts:0,   W:0, sv:7,inv:null,fnp:null, sWs:null,mWs:null, buffs:{}, validFor:"all"},
    sc:       {name:"Shield-Captain",pts:120, W:6, sv:2,inv:4,  fnp:null,
        sWs:[[2,2,4,-1,2,{}]],
        mWs:[[7,2,7,-2,2,{}]],
        buffs:{}, validFor:["cg","cw","sag","cgs"]},
    sc_a:     {name:"SC: Allarus",   pts:130, W:7, sv:2,inv:4,  fnp:null,
        sWs:[[2,2,4,-1,2,{}]],
        mWs:[[6,2,9,-1,3,{}]],
        buffs:{}, validFor:["al","aq"]},
    sc_b:     {name:"SC: Dawneagle", pts:150, W:8, sv:2,inv:4,  fnp:null,
        sWs:[[1,2,10,-3,4.5,{tl:1}]],
        mWs:[[6,2,7,-2,2,{}]],
        buffs:{}, validFor:["vp","ag"]},
    trajann:  {name:"Trajann Valoris",pts:140,W:7, sv:2,inv:4,  fnp:5,
        sWs:[[2,2,5,-2,3,{}]],
        mWs:[[6,2,10,-2,3,{}]],
        buffs:{}, validFor:["cg","cw","sag","cgs"]},
    valerian: {name:"Valerian",       pts:110,W:6, sv:2,inv:4,  fnp:6,
        sWs:[[3,2,4,-1,2,{}]],
        mWs:[[7,2,8,-3,2,{}]],
        buffs:{eApMod:1}, validFor:["cg","cw","sag","cgs"]},
    blade_v:  {name:"BC: Victus",     pts:120,W:6, sv:2,inv:4,  fnp:null,
        sWs:null,
        mWs:[[5,2,6,-3,3,{dev:1}]],
        buffs:{}, validFor:["cg","cw","sag","cgs"]},
    blade_h:  {name:"BC: Hurricanus", pts:120,W:6, sv:2,inv:4,  fnp:null,
        sWs:null,
        mWs:[[9,2,5,-1,1,{sh1:1}]],
        buffs:{}, validFor:["cg","cw","sag","cgs"]},
};

export const UNITS = [
    // ── Custodian Guard (guardian spear) — Stand Vigil: rrw1 on all attacks ────
    {id:"cg4da",uid:"cg",unit:"Custodian Guard",pts:160,pts10:160,m:4,W:3,sv:2,inv:4,fnp:null,
        label:"4m guardian spear (Da: SH1)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[8,2,4,-1,2,{rrw1:1}]],
        mWs:[[20,2,7,-2,2,{sh1:1,rrw1:1}]]},
    {id:"cg4re",uid:"cg",unit:"Custodian Guard",pts:160,pts10:160,m:4,W:3,sv:2,inv:4,fnp:null,
        label:"4m guardian spear (Re: lethal)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[8,2,4,-1,2,{rrw1:1}]],
        mWs:[[20,2,7,-2,2,{let:1,rrw1:1}]]},
    {id:"cg5da",uid:"cg",unit:"Custodian Guard",pts:200,pts10:200,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m guardian spear (Da: SH1)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[10,2,4,-1,2,{rrw1:1}]],
        mWs:[[25,2,7,-2,2,{sh1:1,rrw1:1}]]},
    {id:"cg5re",uid:"cg",unit:"Custodian Guard",pts:200,pts10:200,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m guardian spear (Re: lethal)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[10,2,4,-1,2,{rrw1:1}]],
        mWs:[[25,2,7,-2,2,{let:1,rrw1:1}]]},
    {id:"cg4sh",uid:"cg",unit:"Custodian Guard",pts:160,pts10:160,m:4,W:4,sv:2,inv:4,fnp:null,
        label:"4m sentinel blade + praesidium (W4, Da)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[8,2,4,-1,2,{rrw1:1}]],
        mWs:[[20,2,6,-2,1,{sh1:1,rrw1:1}]]},

    // ── Custodian Wardens ────────────────────────────────────────────────────────
    {id:"cw4da",uid:"cw",unit:"Custodian Wardens",pts:210,pts10:210,m:4,W:3,sv:2,inv:4,fnp:null,
        label:"4m guardian spear (Da: SH1)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[8,2,4,-1,2,{}]],
        mWs:[[20,2,7,-2,2,{sh1:1}]]},
    {id:"cw4re",uid:"cw",unit:"Custodian Wardens",pts:210,pts10:210,m:4,W:3,sv:2,inv:4,fnp:null,
        label:"4m guardian spear (Re: lethal)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[8,2,4,-1,2,{}]],
        mWs:[[20,2,7,-2,2,{let:1}]]},
    {id:"cw4axa",uid:"cw",unit:"Custodian Wardens",pts:210,pts10:210,m:4,W:3,sv:2,inv:4,fnp:null,
        label:"4m castellan axe (Da: SH1)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[8,2,4,-1,2,{}]],
        mWs:[[16,2,9,-1,3,{sh1:1}]]},
    {id:"cw4axr",uid:"cw",unit:"Custodian Wardens",pts:210,pts10:210,m:4,W:3,sv:2,inv:4,fnp:null,
        label:"4m castellan axe (Re: lethal)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[8,2,4,-1,2,{}]],
        mWs:[[16,2,9,-1,3,{let:1}]]},

    // ── Allarus Custodians ────────────────────────────────────────────────────────
    {id:"al2g",uid:"al",unit:"Allarus Custodians",pts:110,pts10:110,m:2,W:4,sv:2,inv:4,fnp:null,
        label:"2m guardian spear (Re: lethal)",
        chars:["none","sc_a"],
        sWs:[[4,2,4,-1,2,{}],[7,2,4,-1,1,{}]],
        mWs:[[10,2,7,-2,2,{let:1}]]},
    {id:"al2gv",uid:"al",unit:"Allarus Custodians",pts:110,pts10:110,m:2,W:4,sv:2,inv:4,fnp:null,
        label:"2m guardian spear vs CHAR/MON/VEH (full rrw)",
        chars:["none","sc_a"],
        sWs:[[4,2,4,-1,2,{rrwf:1}],[7,2,4,-1,1,{rrwf:1}]],
        mWs:[[10,2,7,-2,2,{let:1,rrwf:1}]]},
    {id:"al2ax",uid:"al",unit:"Allarus Custodians",pts:110,pts10:110,m:2,W:4,sv:2,inv:4,fnp:null,
        label:"2m castellan axe vs CHAR/MON/VEH (full rrw)",
        chars:["none","sc_a"],
        sWs:[[4,2,4,-1,2,{rrwf:1}],[7,2,4,-1,1,{rrwf:1}]],
        mWs:[[8,2,9,-1,3,{let:1,rrwf:1}]]},
    {id:"al3g",uid:"al",unit:"Allarus Custodians",pts:165,pts10:165,m:3,W:4,sv:2,inv:4,fnp:null,
        label:"3m guardian spear (Re: lethal)",
        chars:["none","sc_a"],
        sWs:[[6,2,4,-1,2,{}],[11,2,4,-1,1,{}]],
        mWs:[[15,2,7,-2,2,{let:1}]]},
    {id:"al3ax",uid:"al",unit:"Allarus Custodians",pts:165,pts10:165,m:3,W:4,sv:2,inv:4,fnp:null,
        label:"3m castellan axe vs CHAR/MON/VEH (full rrw)",
        chars:["none","sc_a"],
        sWs:[[6,2,4,-1,2,{rrwf:1}],[11,2,4,-1,1,{rrwf:1}]],
        mWs:[[12,2,9,-1,3,{let:1,rrwf:1}]]},

    {id:"cw5da",uid:"cw",unit:"Custodian Wardens",pts:260,pts10:260,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m guardian spear (Da: SH1)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[10,2,4,-1,2,{}]],
        mWs:[[25,2,7,-2,2,{sh1:1}]]},
    {id:"cw5re",uid:"cw",unit:"Custodian Wardens",pts:260,pts10:260,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m guardian spear (Re: lethal)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[10,2,4,-1,2,{}]],
        mWs:[[25,2,7,-2,2,{let:1}]]},
    {id:"cw5axa",uid:"cw",unit:"Custodian Wardens",pts:260,pts10:260,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m castellan axe (Da: SH1)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[10,2,4,-1,2,{}]],
        mWs:[[20,2,9,-1,3,{sh1:1}]]},
    {id:"cw5axr",uid:"cw",unit:"Custodian Wardens",pts:260,pts10:260,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m castellan axe (Re: lethal)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[10,2,4,-1,2,{}]],
        mWs:[[20,2,9,-1,3,{let:1}]]},

    {id:"al5g",uid:"al",unit:"Allarus Custodians",pts:275,pts10:275,m:5,W:4,sv:2,inv:4,fnp:null,
        label:"5m guardian spear (Re: lethal)",
        chars:["none","sc_a"],
        sWs:[[10,2,4,-1,2,{}],[17.5,2,4,-1,1,{}]],
        mWs:[[25,2,7,-2,2,{let:1}]]},
    {id:"al5ax",uid:"al",unit:"Allarus Custodians",pts:275,pts10:275,m:5,W:4,sv:2,inv:4,fnp:null,
        label:"5m castellan axe vs CHAR/MON/VEH (full rrw)",
        chars:["none","sc_a"],
        sWs:[[10,2,4,-1,2,{rrwf:1}],[17.5,2,4,-1,1,{rrwf:1}]],
        mWs:[[20,2,9,-1,3,{let:1,rrwf:1}]]},
    {id:"al6g",uid:"al",unit:"Allarus Custodians",pts:330,pts10:330,m:6,W:4,sv:2,inv:4,fnp:null,
        label:"6m guardian spear (Re: lethal)",
        chars:["none","sc_a"],
        sWs:[[12,2,4,-1,2,{}],[21,2,4,-1,1,{}]],
        mWs:[[30,2,7,-2,2,{let:1}]]},
    {id:"al6ax",uid:"al",unit:"Allarus Custodians",pts:330,pts10:330,m:6,W:4,sv:2,inv:4,fnp:null,
        label:"6m castellan axe vs CHAR/MON/VEH (full rrw)",
        chars:["none","sc_a"],
        sWs:[[12,2,4,-1,2,{rrwf:1}],[21,2,4,-1,1,{rrwf:1}]],
        mWs:[[24,2,9,-1,3,{let:1,rrwf:1}]]},

    // ── Sagittarum Custodians ─────────────────────────────────────────────────────
    {id:"sag5",uid:"sag",unit:"Sagittarum Custodians",pts:225,pts10:225,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m adrastus bolt caliver (SH1)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[15,2,5,-1,2,{sh1:1}]],
        mWs:[[20,2,5,-2,1,{}]]},

    // ── Vertus Praetors ───────────────────────────────────────────────────────────
    {id:"vp2s",uid:"vp",unit:"Vertus Praetors",pts:150,pts10:150,m:2,W:5,sv:2,inv:4,fnp:null,
        label:"2m salvo launcher TL (anti-vehicle)",
        chars:["none","sc_b"],
        sWs:[[2,2,10,-3,4.5,{tl:1}]],
        mWs:[[10,2,7,-2,2,{}]]},
    {id:"vp2h",uid:"vp",unit:"Vertus Praetors",pts:150,pts10:150,m:2,W:5,sv:2,inv:4,fnp:null,
        label:"2m hurricane bolter TL (anti-infantry, full range)",
        chars:["none","sc_b"],
        sWs:[[6,2,4,-1,2,{tl:1}]],
        mWs:[[10,2,7,-2,2,{}]]},
    {id:"vp3s",uid:"vp",unit:"Vertus Praetors",pts:225,pts10:225,m:3,W:5,sv:2,inv:4,fnp:null,
        label:"3m salvo launcher TL (anti-vehicle)",
        chars:["none","sc_b"],
        sWs:[[3,2,10,-3,4.5,{tl:1}]],
        mWs:[[15,2,7,-2,2,{}]]},
    {id:"vp3h",uid:"vp",unit:"Vertus Praetors",pts:225,pts10:225,m:3,W:5,sv:2,inv:4,fnp:null,
        label:"3m hurricane bolter TL",
        chars:["none","sc_b"],
        sWs:[[9,2,4,-1,2,{tl:1}]],
        mWs:[[15,2,7,-2,2,{}]]},

    // ── Venatari Custodians ────────────────────────────────────────────────────────
    {id:"vn3da",uid:"vn",unit:"Venatari Custodians",pts:165,pts10:165,m:3,W:3,sv:2,inv:4,fnp:null,
        label:"3m venatari lance (Da: SH1)",
        chars:["none"],
        sWs:[[6,2,4,-1,2,{}]],
        mWs:[[15,2,7,-2,2,{sh1:1}]]},
    {id:"vn3re",uid:"vn",unit:"Venatari Custodians",pts:165,pts10:165,m:3,W:3,sv:2,inv:4,fnp:null,
        label:"3m venatari lance (Re: lethal)",
        chars:["none"],
        sWs:[[6,2,4,-1,2,{}]],
        mWs:[[15,2,7,-2,2,{let:1}]]},
    {id:"vn3bk",uid:"vn",unit:"Venatari Custodians",pts:165,pts10:165,m:3,W:4,sv:2,inv:4,fnp:null,
        label:"3m tarsis buckler (W4, Da)",
        chars:["none"],
        sWs:[[6,2,6,-1,1,{sh1:1}]],
        mWs:[[15,2,5,-2,1,{sh1:1}]]},
    {id:"vn6re",uid:"vn",unit:"Venatari Custodians",pts:330,pts10:330,m:6,W:3,sv:2,inv:4,fnp:null,
        label:"6m venatari lance (Re: lethal)",
        chars:["none"],
        sWs:[[12,2,4,-1,2,{}]],
        mWs:[[30,2,7,-2,2,{let:1}]]},

    // ── Agamatus Custodians ────────────────────────────────────────────────────────
    {id:"ag3l",uid:"ag",unit:"Agamatus Custodians",pts:225,pts10:225,m:3,W:4,sv:2,inv:4,fnp:null,
        label:"3m lastrum bolt cannon (SH1 shoot)",
        chars:["none","sc_b"],
        sWs:[[9,2,6,-1,1,{sh1:1}]],
        mWs:[[15,2,7,-2,2,{sh1:1}]]},
    {id:"ag3p",uid:"ag",unit:"Agamatus Custodians",pts:225,pts10:225,m:3,W:4,sv:2,inv:4,fnp:null,
        label:"3m twin las-pulsar TL",
        chars:["none","sc_b"],
        sWs:[[6,2,9,-1,2,{tl:1}]],
        mWs:[[15,2,7,-2,2,{sh1:1}]]},
    {id:"ag3a",uid:"ag",unit:"Agamatus Custodians",pts:225,pts10:225,m:3,W:4,sv:2,inv:4,fnp:null,
        label:"3m adrathic devastator",
        chars:["none","sc_b"],
        sWs:[[3,2,7,-2,3,{}]],
        mWs:[[15,2,7,-2,2,{sh1:1}]]},

    {id:"ag6l",uid:"ag",unit:"Agamatus Custodians",pts:450,pts10:450,m:6,W:4,sv:2,inv:4,fnp:null,
        label:"6m lastrum bolt cannon (SH1 shoot)",
        chars:["none","sc_b"],
        sWs:[[18,2,6,-1,1,{sh1:1}]],
        mWs:[[30,2,7,-2,2,{sh1:1}]]},
    {id:"ag6p",uid:"ag",unit:"Agamatus Custodians",pts:450,pts10:450,m:6,W:4,sv:2,inv:4,fnp:null,
        label:"6m twin las-pulsar TL",
        chars:["none","sc_b"],
        sWs:[[12,2,9,-1,2,{tl:1}]],
        mWs:[[30,2,7,-2,2,{sh1:1}]]},

    // ── Aquilon Custodians — Heavy Assault Infantry: rrw1 on ranged (closest tgt)
    {id:"aq3sd",uid:"aq",unit:"Aquilon Custodians",pts:195,pts10:195,m:3,W:4,sv:2,inv:4,fnp:null,
        label:"3m storm bolter + solerite gauntlet (Da: SH1)",
        chars:["none","sc_a"],
        sWs:[[6,2,5,-1,1,{rrw1:1}]],
        mWs:[[15,2,8,-2,2,{sh1:1}]]},
    {id:"aq3sr",uid:"aq",unit:"Aquilon Custodians",pts:195,pts10:195,m:3,W:4,sv:2,inv:4,fnp:null,
        label:"3m storm bolter + solerite gauntlet (Re: lethal)",
        chars:["none","sc_a"],
        sWs:[[6,2,5,-1,1,{rrw1:1}]],
        mWs:[[15,2,8,-2,2,{let:1}]]},
    {id:"aq3dr",uid:"aq",unit:"Aquilon Custodians",pts:195,pts10:195,m:3,W:4,sv:2,inv:4,fnp:null,
        label:"3m twin adrathic TL + solerite gauntlet (Re: lethal)",
        chars:["none","sc_a"],
        sWs:[[3,2,6,-2,3,{tl:1,rrw1:1}]],
        mWs:[[15,2,8,-2,2,{let:1}]]},

    {id:"aq6sd",uid:"aq",unit:"Aquilon Custodians",pts:390,pts10:390,m:6,W:4,sv:2,inv:4,fnp:null,
        label:"6m storm bolter + solerite gauntlet (Da: SH1)",
        chars:["none","sc_a"],
        sWs:[[12,2,5,-1,1,{rrw1:1}]],
        mWs:[[30,2,8,-2,2,{sh1:1}]]},
    {id:"aq6sr",uid:"aq",unit:"Aquilon Custodians",pts:390,pts10:390,m:6,W:4,sv:2,inv:4,fnp:null,
        label:"6m storm bolter + solerite gauntlet (Re: lethal)",
        chars:["none","sc_a"],
        sWs:[[12,2,5,-1,1,{rrw1:1}]],
        mWs:[[30,2,8,-2,2,{let:1}]]},

    // ── Custodian Guard w/ Adrasite & Pyrithite Spears — Stand Vigil: rrw1 ──────
    {id:"cgs_a",uid:"cgs",unit:"CG Spears",pts:250,pts10:250,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m adrasite spear (Re: lethal)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[5,2,5,-2,3,{rrw1:1}]],
        mWs:[[25,2,7,-2,2,{let:1,rrw1:1}]]},
    {id:"cgs_p",uid:"cgs",unit:"CG Spears",pts:250,pts10:250,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m pyrithite spear (melta range, D6+2=5.5)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[5,2,9,-4,5.5,{rrw1:1}]],
        mWs:[[25,2,7,-2,2,{let:1,rrw1:1}]]},
    {id:"cgs_pb",uid:"cgs",unit:"CG Spears",pts:250,pts10:250,m:5,W:3,sv:2,inv:4,fnp:null,
        label:"5m pyrithite spear (std range, D6=3.5)",
        chars:["none","sc","trajann","valerian","blade_v","blade_h"],
        sWs:[[5,2,9,-4,3.5,{rrw1:1}]],
        mWs:[[25,2,7,-2,2,{let:1,rrw1:1}]]},

    // ── Caladius Grav-tank ────────────────────────────────────────────────────────
    {id:"cal_i",uid:"cal",unit:"Caladius Grav-tank",pts:215,pts10:215,m:1,W:14,sv:2,inv:5,fnp:null,
        label:"iliastus accelerator TL (lethal vs non-M/V)",
        chars:["none"],
        sWs:[[4,2,10,-1,3,{tl:1,let:1}],[3,2,6,-1,1,{sh1:1}]],
        mWs:null},
    {id:"cal_b",uid:"cal",unit:"Caladius Grav-tank",pts:215,pts10:215,m:1,W:14,sv:2,inv:5,fnp:null,
        label:"twin blaze cannon TL (lethal vs M/V, D6+2=5.5)",
        chars:["none"],
        sWs:[[4,2,12,-3,5.5,{tl:1,let:1}],[3,2,6,-1,1,{sh1:1}]],
        mWs:null},

    // ── Pallas Grav-attack ────────────────────────────────────────────────────────
    {id:"pal",uid:"pal",unit:"Pallas Grav-attack",pts:105,pts10:105,m:1,W:9,sv:2,inv:5,fnp:null,
        label:"twin blaze cannon (dev+TL, 8A)",
        chars:["none"],
        sWs:[[8,2,5,-1,1,{dev:1,tl:1}]],
        mWs:null},

    // ── Coronus Grav-carrier ──────────────────────────────────────────────────────
    {id:"cor",uid:"cor",unit:"Coronus Grav-carrier",pts:200,pts10:200,m:1,W:16,sv:2,inv:5,fnp:null,
        label:"twin blaze cannon dev TL + lastrum SH1",
        chars:["none"],
        sWs:[[8,2,5,-1,1,{dev:1,tl:1}],[3,2,6,-1,1,{sh1:1}]],
        mWs:null},

    // ── Venerable Contemptor Dreadnought ─────────────────────────────────────────
    {id:"vcd_k",uid:"vcd",unit:"Venerable Contemptor",pts:170,pts10:170,m:1,W:10,sv:2,inv:5,fnp:null,
        label:"Kheres assault cannon (dev)",
        chars:["none"],
        sWs:[[6,2,7,-1,1,{dev:1}]],
        mWs:[[5,2,12,-2,3,{}]]},
    {id:"vcd_m",uid:"vcd",unit:"Venerable Contemptor",pts:170,pts10:170,m:1,W:10,sv:2,inv:5,fnp:null,
        label:"multi-melta (std range, D6=3.5)",
        chars:["none"],
        sWs:[[2,2,9,-4,3.5,{}]],
        mWs:[[5,2,12,-2,3,{}]]},
    {id:"vcd_mr",uid:"vcd",unit:"Venerable Contemptor",pts:170,pts10:170,m:1,W:10,sv:2,inv:5,fnp:null,
        label:"multi-melta (melta range, D6+2=5.5)",
        chars:["none"],
        sWs:[[2,2,9,-4,5.5,{}]],
        mWs:[[5,2,12,-2,3,{}]]},

    // ── Contemptor-Achillus Dreadnought ─────────────────────────────────────────
    {id:"ach_d",uid:"ach",unit:"Contemptor-Achillus",pts:155,pts10:155,m:1,W:10,sv:2,inv:5,fnp:null,
        label:"dreadspear lance (Da: SH1)",
        chars:["none"],
        sWs:[[4,2,5,-1,1,{}],[1,2,9,-2,3,{}]],
        mWs:[[5,2,12,-2,4.5,{sh1:1}]]},
    {id:"ach_r",uid:"ach",unit:"Contemptor-Achillus",pts:155,pts10:155,m:1,W:10,sv:2,inv:5,fnp:null,
        label:"dreadspear lance (Re: lethal)",
        chars:["none"],
        sWs:[[4,2,5,-1,1,{}],[1,2,9,-2,3,{}]],
        mWs:[[5,2,12,-2,4.5,{let:1}]]},

    // ── Contemptor-Galatus Dreadnought ───────────────────────────────────────────
    {id:"gal_d",uid:"gal",unit:"Contemptor-Galatus",pts:165,pts10:165,m:1,W:10,sv:2,inv:4,fnp:null,
        label:"galatus warblade (Da: SH1)",
        chars:["none"],
        sWs:[[3.5,1,6,-1,1,{}]],
        mWs:[[8,2,8,-2,3,{sh1:1}]]},
    {id:"gal_r",uid:"gal",unit:"Contemptor-Galatus",pts:165,pts10:165,m:1,W:10,sv:2,inv:4,fnp:null,
        label:"galatus warblade (Re: lethal)",
        chars:["none"],
        sWs:[[3.5,1,6,-1,1,{}]],
        mWs:[[8,2,8,-2,3,{let:1}]]},

    // ── Telemon Heavy Dreadnought ────────────────────────────────────────────────
    {id:"tel_i",uid:"tel",unit:"Telemon Heavy Dreadnought",pts:225,pts10:225,m:1,W:12,sv:2,inv:4,fnp:null,
        label:"2× iliastus accelerator culverin + spiculus",
        chars:["none"],
        sWs:[[8,2,9,-1,3,{}],[6.5,2,5,0,1,{}]],
        mWs:[[5,2,7,0,1,{}]]},
    {id:"tel_i_rf",uid:"tel",unit:"Telemon Heavy Dreadnought",pts:225,pts10:225,m:1,W:12,sv:2,inv:4,fnp:null,
        label:"2× iliastus + spiculus [+Prioritised Eradication RF2, 12A]",
        chars:["none"],
        sWs:[[12,2,9,-1,3,{}],[6.5,2,5,0,1,{}]],
        mWs:[[5,2,7,0,1,{}]]},
    {id:"tel_s",uid:"tel",unit:"Telemon Heavy Dreadnought",pts:225,pts10:225,m:1,W:12,sv:2,inv:4,fnp:null,
        label:"2× arachnus storm cannon (dev) + spiculus",
        chars:["none"],
        sWs:[[24,2,6,-1,1,{dev:1}],[6.5,2,5,0,1,{}]],
        mWs:[[5,2,7,0,1,{}]]},
    {id:"tel_s_rf",uid:"tel",unit:"Telemon Heavy Dreadnought",pts:225,pts10:225,m:1,W:12,sv:2,inv:4,fnp:null,
        label:"2× storm cannon (dev) + spiculus [+Prioritised Eradication RF6, 36A]",
        chars:["none"],
        sWs:[[36,2,6,-1,1,{dev:1}],[6.5,2,5,0,1,{}]],
        mWs:[[5,2,7,0,1,{}]]},
    {id:"tel_c",uid:"tel",unit:"Telemon Heavy Dreadnought",pts:225,pts10:225,m:1,W:12,sv:2,inv:4,fnp:null,
        label:"2× Telemon caestus (14A at S12, Re: lethal)",
        chars:["none"],
        sWs:[[6.5,2,5,0,1,{}]],
        mWs:[[14,2,12,-2,3,{let:1}],[5,2,7,0,1,{}]]},

    // ── Venerable Land Raider ───────────────────────────────────────────────────
    {id:"vlr",uid:"vlr",unit:"Venerable Land Raider",pts:220,pts10:220,m:1,W:16,sv:2,inv:null,fnp:null,
        label:"2× lascannon + twin heavy bolter SH1",
        chars:["none"],
        sWs:[[4,2,12,-3,4.5,{}],[3,2,5,-1,2,{sh1:1,tl:1}]],
        mWs:null},

    // ── Prosecutors (Sisters – Talons support) ───────────────────────────────────
    {id:"pro4",uid:"pro",unit:"Prosecutors",pts:40,pts10:40,m:4,W:1,sv:3,inv:null,fnp:null,
        label:"4m boltgun (anti-psyker: dev+precision)",
        chars:["none"],
        sWs:[[4,3,4,0,1,{}]],
        mWs:[[8,3,3,0,1,{}]]},

    {id:"pro10",uid:"pro",unit:"Prosecutors",pts:85,pts10:85,m:10,W:1,sv:3,inv:null,fnp:null,
        label:"10m boltgun",
        chars:["none"],
        sWs:[[10,3,4,0,1,{}]],
        mWs:[[20,3,3,0,1,{}]]},

    // ── Vigilators (Sisters – Talons support) ───────────────────────────────────
    {id:"vig4",uid:"vig",unit:"Vigilators",pts:45,pts10:45,m:4,W:1,sv:3,inv:null,fnp:null,
        label:"4m executioner greatblade (anti-psyker dev, fights first)",
        chars:["none"],
        sWs:null,
        mWs:[[8,3,5,-2,2,{dev:1}]]},

    {id:"vig10",uid:"vig",unit:"Vigilators",pts:100,pts10:100,m:10,W:1,sv:3,inv:null,fnp:null,
        label:"10m executioner greatblade (anti-psyker dev, fights first)",
        chars:["none"],
        sWs:null,
        mWs:[[20,3,5,-2,2,{dev:1}]]},

    // ── Witchseekers (Sisters – Talons support) ─────────────────────────────────
    {id:"wit4",uid:"wit",unit:"Witchseekers",pts:45,pts10:45,m:4,W:1,sv:3,inv:null,fnp:null,
        label:"4m witchseeker flamer torrent (auto-hit)",
        chars:["none"],
        sWs:[[14,1,4,0,1,{}]],
        mWs:[[8,3,3,0,1,{}]]},

    {id:"wit10",uid:"wit",unit:"Witchseekers",pts:100,pts10:100,m:10,W:1,sv:3,inv:null,fnp:null,
        label:"10m witchseeker flamer torrent (auto-hit)",
        chars:["none"],
        sWs:[[35,1,4,0,1,{}]],
        mWs:[[20,3,3,0,1,{}]]},

    // ── Character solo eval ───────────────────────────────────────────────────────
    {id:"bc_v",uid:"bc",unit:"Blade Champion",pts:120,pts10:120,m:1,W:6,sv:2,inv:4,fnp:null,
        label:"Victus: S6 AP-3 D3 dev",
        chars:["none"],
        sWs:null,
        mWs:[[5,2,6,-3,3,{dev:1}]]},
    {id:"bc_h",uid:"bc",unit:"Blade Champion",pts:120,pts10:120,m:1,W:6,sv:2,inv:4,fnp:null,
        label:"Hurricanus: 9A S5 AP-1 D1 SH1",
        chars:["none"],
        sWs:null,
        mWs:[[9,2,5,-1,1,{sh1:1}]]},
    {id:"bc_b",uid:"bc",unit:"Blade Champion",pts:120,pts10:120,m:1,W:6,sv:2,inv:4,fnp:null,
        label:"Behemor: 6A S7 AP-2 D2 Precision",
        chars:["none"],
        sWs:null,
        mWs:[[6,2,7,-2,2,{}]]},
    {id:"sc01",uid:"sc",unit:"Shield-Captain",pts:120,pts10:120,m:1,W:6,sv:2,inv:4,fnp:null,
        label:"guardian spear (7A melee, Re: lethal)",
        chars:["none"],
        sWs:[[2,2,4,-1,2,{}]],
        mWs:[[7,2,7,-2,2,{let:1}]]},
    {id:"sca01",uid:"sca",unit:"SC: Allarus",pts:130,pts10:130,m:1,W:7,sv:2,inv:4,fnp:null,
        label:"castellan axe (6A S9, Re: lethal)",
        chars:["none"],
        sWs:[[2,2,4,-1,2,{}]],
        mWs:[[6,2,9,-1,3,{let:1}]]},
    {id:"scb01",uid:"scb",unit:"SC: Dawneagle",pts:150,pts10:150,m:1,W:8,sv:2,inv:4,fnp:null,
        label:"salvo launcher TL + interceptor lance",
        chars:["none"],
        sWs:[[1,2,10,-3,4.5,{tl:1}]],
        mWs:[[6,2,7,-2,2,{let:1}]]},
    {id:"tj01",uid:"tj",unit:"Trajann Valoris",pts:140,pts10:140,m:1,W:7,sv:2,inv:4,fnp:5,
        label:"Watcher's Axe (6A S10 AP-2 D3)",
        chars:["none"],
        sWs:[[2,2,5,-2,3,{}]],
        mWs:[[6,2,10,-2,3,{let:1}]]},
    {id:"val01",uid:"val",unit:"Valerian",pts:110,pts10:110,m:1,W:6,sv:2,inv:4,fnp:6,
        label:"Gnosis (7A S8 AP-3 D2, Re: lethal)",
        chars:["none"],
        sWs:[[3,2,4,-1,2,{}]],
        mWs:[[7,2,8,-3,2,{let:1}]]},
];

// ─── DETACHMENTS ──────────────────────────────────────────────────────────────
export const DETACHMENTS = [
    {id:"talons",  dp:3, name:"Talons of the Emperor", disp:"Take and Hold",
        desc:"Revered Companions: Custodes aura gives Sisters +1 hit. Sisters aura gives Custodes FNP 5+ vs mortal wounds.",
        affects:{uids:["pro","vig","wit"], bhBonus:1}},
    {id:"shield_h",dp:2, name:"Shield Host", disp:"Purge the Foe",
        desc:"Martial Mastery: choose each battle round — 5+ crits OR +1 AP on Ka'tah melee attacks.",
        options:[
            {key:"crit", label:"5+ crits",   affects:{all:true, ch5m:true}},
            {key:"ap",   label:"+1 AP melee", affects:{all:true, ap1m:true}},
        ]},
    {id:"lions",   dp:2, name:"Lions of the Emperor", disp:"Disruption",
        desc:"[Unique: Lions] Against All Odds: +1 hit and +1 wound when no other friendly within 6\" (non-vehicles).",
        affects:{all:true, bhBonus:1, wBonus:1}},
    {id:"auric",   dp:2, name:"Auric Champions", disp:"Priority Assets",
        desc:"Assemblage of Might: +1 wound for Character units vs one designated enemy unit per Command phase.",
        affects:null},
    {id:"solar",   dp:2, name:"Solar Spearhead", disp:"Take and Hold",
        desc:"[Unique: Armoury] Auric Armour: vehicles OC+2 at full wounds; re-roll hit 1 when damaged, re-roll wound 1 below half.",
        affects:null},
    {id:"null_m",  dp:2, name:"Null Maiden Vigil", disp:"Recon",
        desc:"Creeping Dread: Anathema units impose battle-shock on nearby psykers and below-strength units.",
        affects:null},
    {id:"moritoi", dp:1, name:"Might of the Moritoi", disp:"Purge the Foe",
        desc:"[Unique: Armoury] March of the Honoured Dead: Walker units +2\" M, +1 advance/charge rolls.",
        affects:null},
    {id:"silent",  dp:1, name:"Silent Hunters", disp:"Recon",
        desc:"Skin-Crawling Disorientation: Anathema units can advance + start actions; Ceaseless Vigilance marks enemy units.",
        affects:null},
    {id:"tharanatoi",dp:1,name:"Tharanatoi Hammerblow",disp:"Priority Assets",
        desc:"[Unique: Lions] The Hammer Falls: Terminator units that made an ingress move can re-roll charge rolls.",
        affects:null},
];

// Unit accent colours (keyed by uid)
export const UC = {
    cg:"#fbbf24",  cw:"#f59e0b",  al:"#d97706",  sag:"#7dd3fc",
    vp:"#fb923c",  vn:"#fde68a",  ag:"#f97316",  aq:"#94a3b8",
    cgs:"#fca5a5", cal:"#22d3ee", pal:"#67e8f9",  cor:"#0891b2",
    vcd:"#a78bfa", ach:"#c084fc", gal:"#e879f9",  tel:"#818cf8",
    vlr:"#64748b", pro:"#d1d5db", vig:"#9ca3af",  wit:"#6b7280",
    bc:"#f472b6",  sc:"#fb923c",  sca:"#ea580c",  scb:"#c2410c",
    tj:"#ef4444",  val:"#22c55e",
};
