// ─── FACTION: LEAGUES OF VOTANN ───────────────────────────────────────────────
// Last updated: Faction Pack v1.1 (legal 2026-08-03); MFM v1.3 (legal 2026-08-26); no weapon stat changes
// MFM v1.3 pts deltas: Hearthkyn Warriors 10m ▼-10, Cthonian Beserks 5m ▼-5/10m ▼-10,
// Brôkhyr Thunderkyn 6m ▲+10, Steeljacks HVD 6m ▲+10, Steeljacks Melee 6m ▼-10,
// Cthonian Earthshakers 2m ▼-10, Kapricus Defender 1-model ▲+5 (pts10 = pre-v1.3 value)
// (shared TARGETS array lives in ../targets.js, not here - it's used by all factions)

// Characters: each has pts, durability, weapons, buffs applied to unit weapons, valid uids
// buffs.let = Lethal Hits on all unit weapons; buffs.sh1m = SH1 on unit melee weapons
// buffs.unitFnp = override unit FNP with this value; buffs.kahlW = Ironskein bonus wounds
export const CHARS={
    none:     {name:"None",      pts:0,  W:0, sv:7,inv:null,fnp:null, sWs:null,mWs:null, buffs:{}, validFor:"all"},
    kahl:     {name:"Kâhl",      pts:65, W:4, sv:3,inv:4,  fnp:null,
        sWs:[[4,2,4,0,1,{}]],
        mWs:[[4,2,5,-2,2,{}]],
        buffs:{let:1,kahlW:2}, validFor:["hk","hg"]},
    champion: {name:"Einhyr Champion", pts:65, W:5, sv:2,inv:4,fnp:null,
        sWs:[[4,2,4,0,1,{}]],
        mWs:[[3,3,12,-3,4.5,{}],[2.25,2,99,0,1,{dev:1}]],
        buffs:{}, validFor:["hg"]},
    grimnyr:  {name:"Grimnyr",   pts:65, W:6, sv:4,inv:4,  fnp:null,
        // Grimnyr: focused wrath 6A + stave 2A; 2×CORV: bolter 4A + CCW 1A
        sWs:[[6,3,6,-2,2,{}],[4,4,4,0,1,{}]],
        mWs:[[2,3,7,-1,2,{}],[2,4,3,0,1,{}]],
        buffs:{unitFnp:5}, validFor:["hk"]},
    uthar:    {name:"Ûthar",     pts:90, W:5, sv:3,inv:4,  fnp:null,
        // Volkanite 3A + AF pseudo-attack shoot; Blade 5A Dev + AF pseudo melee
        sWs:[[3,2,5,0,1,{dev:1}],[1,2,99,0,1,{dev:1}]],
        mWs:[[5,2,6,-3,2,{dev:1}],[1,2,99,-3,2,{dev:1}]],
        buffs:{unitInv:5}, validFor:["hk","hg"]},
    berehk:   {name:"Berehk",    pts:95, W:5, sv:5,inv:5,  fnp:null,
        sWs:null,
        mWs:[[4,2,10,-2,4,{av3:1,am3:1}],[8,2,7,-2,2,{}],[2,2,6,-2,1,{}]],
        buffs:{sh1m:1}, validFor:["bs"]},
    ironmaster:{name:"Iron-Master",pts:75,W:8,sv:4,inv:null,fnp:null,
        // grav rifle 3A BS3+ rrw1; Asst las-beam 1A BS4+; E-COG bolt pistol 1A BS3+
        // melee: grav hammer 3A + Asst CCW 1A + E-COG CCW 1A + plasma torch 1A + manip arms 3A
        sWs:[[3,3,5,-1,3,{av3:1,am3:1,rrw1:1}],[1,4,6,-3,1,{rrw1:1}],[1,3,4,0,1,{rrw1:1}]],
        mWs:[[3,4,9,-1,3,{av3:1,am3:1}],[1,4,3,0,1,{}],[1,4,6,-3,2,{}],[3,4,3,0,1,{}]],
        buffs:{rrw1:1}, validFor:["tk"]},
};

// Units: base stats only, no char baked in. chars = valid char keys for this unit.
// sWs/mWs are the unit's own weapons at base size.
export const UNITS=[
    // ── Hearthkyn Warriors ──────────────────────────────────────────────────────
    {id:"hk06",uid:"hk",unit:"Hearthkyn Warriors",pts:90,pts10:100,m:10,W:1,sv:4,inv:null,fnp:6,
        label:"10m max: rotary+magna+ion×7+Theyn pistol",
        chars:["none","kahl","champion","grimnyr","uthar"],
        sWs:[[6,4,6,-1,1,{sh1:1}],[1,4,12,-3,5,{dev:1}],[7,4,5,-2,1,{}],[1,4,8,-2,1,{}]],
        mWs:[[7,4,4,0,1,{}],[4,4,4,-2,1,{}],[2,4,5,-2,2,{}]]},
    {id:"hk07",uid:"hk",unit:"Hearthkyn Warriors",pts:90,pts10:100,m:10,W:1,sv:4,inv:null,fnp:6,
        label:"10m max: rotary+plasma beamer+ion×7+Theyn pistol",
        chars:["none","kahl","champion","grimnyr","uthar"],
        sWs:[[6,4,6,-1,1,{sh1:1}],[1,4,8,-3,2,{shd3:1}],[7,4,5,-2,1,{}],[1,4,8,-2,1,{}]],
        mWs:[[7,4,4,0,1,{}],[4,4,4,-2,1,{}],[2,4,5,-2,2,{}]]},

    // ── Einhyr Hearthguard ──────────────────────────────────────────────────────
    {id:"hg12",uid:"hg",unit:"Einhyr Hearthguard",pts:270,pts10:270,m:10,W:2,sv:2,inv:5,fnp:null,
        label:"10m plasma+concussion gauntlet",
        chars:["none","kahl","champion","uthar"],
        sWs:[[20,3,7,-3,2,{}],[20,3,3,0,1,{}]],
        mWs:[[20,3,8,-2,2,{}]]},
    {id:"hg05",uid:"hg",unit:"Einhyr Hearthguard",pts:130,pts10:135,m:5,W:2,sv:2,inv:5,fnp:null,
        label:"5m plasma+concussion gauntlet",
        chars:["none","kahl","champion","uthar"],
        sWs:[[10,3,7,-3,2,{}],[10,3,3,0,1,{}]],
        mWs:[[10,3,8,-2,2,{}]]},

    // ── Cthonian Beserks ────────────────────────────────────────────────────────
    {id:"bs07",uid:"bs",unit:"Cthonian Beserks",pts:190,pts10:200,m:10,W:1,sv:5,inv:null,fnp:4,
        label:"10m concussion maul",
        chars:["none","berehk"],
        sWs:null,
        mWs:[[30,4,5,-2,3,{av3:1,am3:1}]]},
    {id:"bs09",uid:"bs",unit:"Cthonian Beserks",pts:190,pts10:200,m:10,W:1,sv:5,inv:null,fnp:4,
        label:"10m 8×maul + 2×twin concussion gauntlet",
        chars:["none","berehk"],
        sWs:null,
        mWs:[[24,4,5,-2,3,{av3:1,am3:1}],[8,4,9,-2,2,{tl:1}]]},
    {id:"bs_mole",uid:"bs",unit:"Cthonian Beserks",pts:190,pts10:200,m:10,W:1,sv:5,inv:null,fnp:4,
        label:"10m maul + mole grenades (indirect)",
        chars:["none","berehk"],
        sWs:[[7,5,5,-1,1,{dev:1}]],
        mWs:[[24,4,5,-2,3,{av3:1,am3:1}]]},
    {id:"bs05",uid:"bs",unit:"Cthonian Beserks",pts:95,pts10:100,m:5,W:1,sv:5,inv:null,fnp:4,
        label:"5m concussion maul [Sagitaur delivery]",
        chars:["none"],
        sWs:null,
        mWs:[[15,4,5,-2,3,{av3:1,am3:1}]]},

    // ── Brôkhyr Thunderkyn ──────────────────────────────────────────────────────
    {id:"tk05",uid:"tk",unit:"Brôkhyr Thunderkyn",pts:170,pts10:160,m:6,W:2,sv:3,inv:null,fnp:null,
        label:"6m bolt cannon (SH2)",
        chars:["none","ironmaster"],
        sWs:[[18,4,6,-1,2,{sh2:1}]],
        mWs:[[12,4,4,0,1,{}]]},
    {id:"tk06",uid:"tk",unit:"Brôkhyr Thunderkyn",pts:170,pts10:160,m:6,W:2,sv:3,inv:null,fnp:null,
        label:"6m grav blast cannon (anti-veh/mon 3+)",
        chars:["none","ironmaster"],
        sWs:[[12,4,5,-2,3,{av3:1,am3:1}]],
        mWs:[[12,4,4,0,1,{}]]},
    {id:"tk07",uid:"tk",unit:"Brôkhyr Thunderkyn",pts:170,pts10:160,m:6,W:2,sv:3,inv:null,fnp:null,
        label:"6m SP conv beamer >12\" (4+ crit+lethal)",
        chars:["none","ironmaster"],
        sWs:[[12,4,7,-2,3,{conv:1}]],
        mWs:[[12,4,4,0,1,{}]]},
    {id:"tk08",uid:"tk",unit:"Brôkhyr Thunderkyn",pts:170,pts10:160,m:6,W:2,sv:3,inv:null,fnp:null,
        label:"6m SP conv beamer <12\" (normal hits)",
        chars:["none","ironmaster"],
        sWs:[[12,4,7,-2,3,{con:1}]],
        mWs:[[12,4,4,0,1,{}]]},
    {id:"tk03b",uid:"tk",unit:"Brôkhyr Thunderkyn",pts:80,pts10:80,m:3,W:2,sv:3,inv:null,fnp:null,
        label:"3m bolt cannon (SH2)",
        chars:["none","ironmaster"],
        sWs:[[9,4,6,-1,2,{sh2:1}]],
        mWs:[[6,4,4,0,1,{}]]},
    {id:"tk03g",uid:"tk",unit:"Brôkhyr Thunderkyn",pts:80,pts10:80,m:3,W:2,sv:3,inv:null,fnp:null,
        label:"3m grav blast cannon (anti-veh/mon 3+)",
        chars:["none","ironmaster"],
        sWs:[[6,4,5,-2,3,{av3:1,am3:1}]],
        mWs:[[6,4,4,0,1,{}]]},
    {id:"tk03c",uid:"tk",unit:"Brôkhyr Thunderkyn",pts:80,pts10:80,m:3,W:2,sv:3,inv:null,fnp:null,
        label:"3m SP conv beamer >12\"",
        chars:["none","ironmaster"],
        sWs:[[6,4,7,-2,3,{conv:1}]],
        mWs:[[6,4,4,0,1,{}]]},

    // ── Ironkin Steeljacks HVD ──────────────────────────────────────────────────
    {id:"sv03",uid:"sv",unit:"Steeljacks HVD",pts:170,pts10:160,m:6,W:3,sv:2,inv:null,fnp:null,
        label:"6m HVD (dev wounds) + plasma knife",
        chars:["none"],
        sWs:[[36,4,6,-1,1,{dev:1}]],
        mWs:[[12,3,6,-2,1,{}]]},

    // ── Ironkin Steeljacks Melee ─────────────────────────────────────────────────
    {id:"sm06",uid:"sm",unit:"Steeljacks Melee",pts:150,pts10:160,m:6,W:3,sv:2,inv:null,fnp:null,
        label:"6m plasma sword (SH1)",
        chars:["none"],
        sWs:null,
        mWs:[[36,3,6,-2,1,{sh1:1}],[12,4,4,0,1,{}]]},
    {id:"sm05",uid:"sm",unit:"Steeljacks Melee",pts:150,pts10:160,m:6,W:3,sv:2,inv:null,fnp:null,
        label:"6m concussion gauntlet",
        chars:["none"],
        sWs:null,
        mWs:[[18,4,10,-2,2,{}],[12,4,4,0,1,{}]]},

    // ── Hernkyn Yaegirs ──────────────────────────────────────────────────────────
    {id:"ya01",uid:"ya",unit:"Hernkyn Yaegirs",pts:90,pts10:90,m:10,W:1,sv:5,inv:null,fnp:null,
        label:"10m bolt shotgun (default)",
        chars:["none"],
        sWs:[[20,4,5,0,1,{}]],
        mWs:[[10,4,4,0,1,{}]]},
    {id:"ya02",uid:"ya",unit:"Hernkyn Yaegirs",pts:90,pts10:90,m:10,W:1,sv:5,inv:null,fnp:null,
        label:"10m max: shotgun×8+magna+APM",
        chars:["none"],
        sWs:[[16,4,5,0,1,{}],[1,4,5,-2,2,{}],[1,4,6,-2,3.5,{av3:1,am3:1}]],
        mWs:[[10,4,4,0,1,{}]]},

    // ── Hernkyn Pioneers ─────────────────────────────────────────────────────────
    {id:"pi_ft2",uid:"pi",unit:"Hernkyn Pioneers",pts:160,pts10:160,m:6,W:3,sv:4,inv:null,fnp:null,
        label:"6m shotgun+magna+HYLas+ion (mixed)",
        chars:["none"],
        sWs:[[12,4,5,0,1,{}],[18,4,7,-1,2,{}],[6,4,6,-1,1,{sh1:1}],[2.5,4,8,-2,1,{}]],
        mWs:[[12,4,4,-2,1,{}]]},
    {id:"pi_ft3",uid:"pi",unit:"Hernkyn Pioneers",pts:160,pts10:160,m:6,W:3,sv:4,inv:null,fnp:null,
        label:"6m shotgun+magna+2×HYLas (max rotary)",
        chars:["none"],
        sWs:[[12,4,5,0,1,{}],[18,4,7,-1,2,{}],[12,4,6,-1,1,{sh1:1}]],
        mWs:[[12,4,4,-2,1,{}]]},
    {id:"pi03",uid:"pi",unit:"Hernkyn Pioneers",pts:80,pts10:80,m:3,W:3,sv:4,inv:null,fnp:null,
        label:"3m shotgun+magna (default)",
        chars:["none"],
        sWs:[[6,4,5,0,1,{}],[9,4,7,-1,2,{}]],
        mWs:[[6,4,4,-2,1,{}]]},

    // ── Cthonian Earthshakers ────────────────────────────────────────────────────
    {id:"es01",uid:"es",unit:"Cthonian Earthshakers",pts:100,pts10:110,m:2,W:6,sv:4,inv:null,fnp:null,
        label:"2m breacher ordnance (blast+dev)",
        chars:["none"],
        sWs:[[4.5,4,10,-1,2,{dev:1}]],
        mWs:[[8,3,5,-2,1,{}]]},
    {id:"es02",uid:"es",unit:"Cthonian Earthshakers",pts:100,pts10:110,m:2,W:6,sv:4,inv:null,fnp:null,
        label:"2m tremor shells (blast)",
        chars:["none"],
        sWs:[[7.5,4,6,-1,1,{}]],
        mWs:[[8,3,5,-2,1,{}]]},

    // ── Hekaton Land Fortress ────────────────────────────────────────────────────
    {id:"hf01",uid:"hf",unit:"Hekaton Land Fortress",pts:250,pts10:240,m:1,W:16,sv:2,inv:null,fnp:null,
        label:"SP conv beamer + 2×twin bolt + MATR",
        chars:["none"],
        sWs:[[4,4,10,-2,4,{con:1,let:1}],[6,4,6,-1,2,{sh2:1,tl:1}],[6,4,7,-1,2,{sh1:1}]],
        mWs:null},
    {id:"hf02",uid:"hf",unit:"Hekaton Land Fortress",pts:250,pts10:240,m:1,W:16,sv:2,inv:null,fnp:null,
        label:"Heavy magna-rail + 2×twin bolt + MATR",
        chars:["none"],
        sWs:[[2,3,18,-4,7,{dev:1}],[6,4,6,-1,2,{sh2:1,tl:1}],[6,4,7,-1,2,{sh1:1}]],
        mWs:null},

    // ── Sagitaur ─────────────────────────────────────────────────────────────────
    {id:"sg01",uid:"sg",unit:"Sagitaur",pts:85,pts10:90,m:1,W:9,sv:3,inv:null,fnp:null,
        label:"HYLas beam cannon + twin bolt cannon",
        chars:["none"],
        sWs:[[2,4,12,-3,4.5,{}],[3,4,6,-1,2,{sh2:1,tl:1}]],
        mWs:null},
    {id:"sg02",uid:"sg",unit:"Sagitaur",pts:85,pts10:90,m:1,W:9,sv:3,inv:null,fnp:null,
        label:"L7 + Sagitaur missile + twin bolt cannon",
        chars:["none"],
        sWs:[[3.5,4,4,0,1,{}],[1,4,9,-2,3.5,{}],[2,4,10,-3,3,{}],[3,4,6,-1,2,{sh2:1,tl:1}]],
        mWs:null},
    {id:"sg03",uid:"sg",unit:"Sagitaur",pts:85,pts10:90,m:1,W:9,sv:3,inv:null,fnp:null,
        label:"MATR autocannon + twin bolt cannon",
        chars:["none"],
        sWs:[[6,4,7,-1,2,{}],[3,4,6,-1,2,{sh2:1,tl:1}]],
        mWs:null},

    // ── Kapricus Defender ────────────────────────────────────────────────────────
    {id:"kd01",uid:"kd",unit:"Kapricus Defender",pts:70,pts10:65,m:1,W:7,sv:4,inv:null,fnp:null,
        label:"Magna-rail cannon + twin magna-coil",
        chars:["none"],
        sWs:[[1,4,14,-4,4.5,{dev:1}],[3,4,7,-1,2,{tl:1}]],
        mWs:null},
    {id:"kd02",uid:"kd",unit:"Kapricus Defender",pts:70,pts10:65,m:1,W:7,sv:4,inv:null,fnp:null,
        label:"HYLas rotary + twin magna-coil",
        chars:["none"],
        sWs:[[6,4,6,-1,2,{sh1:1}],[3,4,7,-1,2,{tl:1}]],
        mWs:null},

    // ── Buri Aegnirssen ──────────────────────────────────────────────────────────
    {id:"bu01",uid:"bu",unit:"Buri Aegnirssen",pts:95,pts10:95,m:1,W:5,sv:3,inv:4,fnp:null,
        label:"Strike: S12 AP-3 D3",
        chars:["none"],
        sWs:null,
        mWs:[[5,2,12,-3,3,{}]]},
    {id:"bu02",uid:"bu",unit:"Buri Aegnirssen",pts:95,pts10:95,m:1,W:5,sv:3,inv:4,fnp:null,
        label:"Sweep: S7 AP-2 D1 ×10",
        chars:["none"],
        sWs:null,
        mWs:[[10,2,6,-2,1,{}]]},

    // ── Einhyr Champion (solo attach eval) ───────────────────────────────────────
    {id:"ch01",uid:"ch",unit:"Einhyr Champion",pts:65,pts10:70,m:1,W:5,sv:2,inv:4,fnp:null,
        label:"1m solo — attach eval only",
        chars:["none"],
        sWs:[[4,2,4,0,1,{}]],
        mWs:[[3,3,12,-3,4.5,{}],[2.25,2,99,0,1,{dev:1}]]},

    // ── Arkanyst Evaluator ───────────────────────────────────────────────────────
    {id:"ak01",uid:"ak",unit:"Arkanyst Evaluator",pts:70,pts10:65,m:1,W:4,sv:3,inv:null,fnp:null,
        label:"Overcharge (AP-3 D3 · SH1)",
        chars:["none"],
        sWs:[[3,2,8,-3,3,{sh1:1}]],
        mWs:[[1,4,3,0,1,{}]]},
];

// ─── DETACHMENTS ──────────────────────────────────────────────────────────────
export const DETACHMENTS=[
    {id:"trailblazers",dp:1,name:"Armoured Trailblazers",disp:"Disruption",
        desc:"Scouts 6\" on Sagitaurs. Positional — no damage calc impact.",affects:null},
    {id:"farseekers",dp:1,name:"Farseekers",disp:"Reconnaissance",
        desc:"+1 hit for Hernkyn (Pioneers, Yaegirs, Kapricus) within 12\".",
        affects:{uids:["pi","ya","kd"],bhBonus:1}},
    {id:"hg_covenant",dp:1,name:"Hearthguard Covenant",disp:"Priority Assets",
        desc:"Re-roll wound 1s ranged for Kâhl/Champion/HG/Ûthar within 9\". Ironskein +2W to Kâhl.",
        affects:{uids:["hg"],charRrw1Shoot:["kahl","uthar","champion"],rrw1Shoot:true}},
    {id:"brandfast",dp:2,name:"Brandfast Oathband",disp:"Take and Hold",
        desc:"Firebase Control SH1 aura on Transports. No direct damage calc impact.",affects:null},
    {id:"delve",dp:2,name:"Dêlve Assault Shift",disp:"Purge the Foe",
        desc:"Beserks deep strike. Cyberstimm gives Beserks re-roll wound 1s in melee.",
        affects:{uids:["bs"],rrw1:true}},
    {id:"hearthfyre",dp:2,name:"Hearthfyre Arsenal",disp:"Priority Assets",
        desc:"1YP: re-roll hit 1s for Thunderkyn/Steeljacks/Arkanyst shooting.",affects:null},
    {id:"mercenary",dp:2,name:"Mercenary Oathband",disp:"Take and Hold",
        desc:"YP flip mechanic. Privateer Arsenal: rrh1+rrw1 for any infantry shooting.",affects:null},
    {id:"needgaard",dp:2,name:"Needgaârd Oathband",disp:"Purge the Foe",
        desc:"+1YP per enemy unit destroyed. Huntr's Mark: rrh1+rrw1 shooting 1CP.",affects:null},
    {id:"persecution",dp:2,name:"Persecution Prospect",disp:"Disruption",
        desc:"Guerrilla Adepts assail/pin mechanic. No direct damage calc impact.",affects:null},
    {id:"hearthband",dp:3,name:"Hearthband",disp:"Priority Assets",
        desc:"Re-roll wound 1s all weapons targeting closest/engagement. Kâhl/HG/Ûthar +1AP.",
        affects:{all:true,rrw1:true,ap1uids:["hg"],ap1chars:["kahl","uthar"]}},
];

// Unit accent colours (keyed by uid)
export const UC={
    hk:"#818cf8",hg:"#a78bfa",bs:"#f472b6",tk:"#fbbf24",sv:"#34d399",
    sm:"#2dd4bf",ya:"#60a5fa",pi:"#38bdf8",es:"#fb923c",
    hf:"#f87171",sg:"#c084fc",kd:"#a3e635",bu:"#e879f9",ak:"#22d3ee",ch:"#f59e0b",
};
